### ISSUE TITLE
Not all tests are available after configuring

### ISSUE THREAD

**Issue by tobiasleibner** [dune-community/dune-xt#16]
For some reason, after the initial ``dunecontrol`` run, there are only about 500 tests included in ``test_binaries``. After another ``cmake`` run, this number increases to about 800. The tests that show up only after the additional ``cmake`` are all dependent on some ``HAVE_*``, e.g, a lot of tests dependent on ``dune-alugrid`` do not show up before the second ``cmake`` run. 
Probably the reason is our python test expansion (.tpl files to tpl.cc files). We should fix this or at least include an additional ``cmake`` run before building the tests in our CI setup (though this will probably make #14 worse).

**Comment by renefritze** [comment]
Indeed the problem is that for the generation to work properly, python needs to look into the cmake cache at configure time where the template expansion runs. Running the python stuff "last" in cmake doesn't work for all checks apparently though since some results only are in the cache after python runs. The second cmake run then adds nothing to the cache, but python can now see all of the cached items.

**Comment by tobiasleibner** [comment]
Moved to the gitlab repository.
